### ISSUE TITLE
Update for latest React version

### ISSUE THREAD

**Issue by Vladimirovici** [JMcAmmond/react-select-datepicker#10]
Hey, first of all good job on the component 😁 
Would it be possible for you to update it so that it works with the latest version of React? (v17.0.2 at the time of writing this)

I tried a quick test in stackblitz and for react 16.8.0 everything works, but breaks on this latest version with the following error:
```
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
```

![image](https://user-images.githubusercontent.com/17068286/141093217-e28287ad-8015-4b63-93a8-5c9d2dd40a9d.png)

**Comment by JMcAmmond** [comment]
Thanks for letting me know. This package has become a little outdated. I have redesigned the component with version 2.0.0 and it should now work with the latest version of react.
